export default function getAllProducts() {
  return [
    {
      id: "001",
      slug: "jaket-fleece-ritsleting-dua-warna-man",
      name: "Jaket Fleece Ritsleting | Dua Warna",
      category: "Men's",
      price: 399_000,
      stock: 100,
      imageUrl:
        "https://image.uniqlo.com/UQ/ST3/id/imagesgoods/469956/item/idgoods_07_469956_3x4.jpg?width=369",
      description: `Bahan dengan kesan tebal di bagian tubuh. Kerah tegak yang sempurna untuk menjaga leher Anda tetap hangat, didesain dengan cermat terutama pada tinggi kerah dan interlining. Aksen piping di ujung pergelangan tangan dan hem untuk mencegah angin masuk dan menjaga kehangatan di dalamnya. Dapat dicuci dengan mesin untuk memudahkan perawatan.`,
    },
    {
      id: "002",
      slug: "heattech-ultra-hangat-t-shirt-kerah-tinggi-men",
      name: "HEATTECH Ultra Hangat T-Shirt Kerah Tinggi",
      category: "Men's",
      price: 209_000,
      stock: 5,
      imageUrl: `https://image.uniqlo.com/UQ/ST3/id/imagesgoods/461012/item/idgoods_01_461012_3x4.jpg?width=369`,
      description: `Produk ini 2,25 kali lebih hangat dari 'HEATTECH' reguler, berdasarkan nilai CLO yang menunjukkan insulasi termal pakaian, dibandingkan dengan 'HEATTECH' biasa. Dilengkapi dengan bahan ringan, lembut, dan lining brush yang lebih 'breathable', serta Ultra Stretch yang merenggang mengikuti gerak tubuh untuk kenyamanan luar biasa. Selain itu, produk ini mampu menyerap kelembapan sehingga tetap terasa sejuk, dengan siluet yang menyerupai t-shirt lengan panjang atau sweater yang bisa dikenakan sendirinya. Harap diperhatikan, produk ini tidak dapat dikembalikan.`,
    },
    {
      id: "003",
      slug: "pullover-sweat-hoodie-men",
      name: "Pullover Sweat Hoodie",
      category: "Men's",
      price: 499_000,
      stock: 0,
      imageUrl: `https://image.uniqlo.com/UQ/ST3/id/imagesgoods/444967/item/idgoods_31_444967_3x4.jpg?width=369`,
      description: `Bahan halus dengan kesan yang premium, dilengkapi desain tudung berkontur, serta saku di bagian samping yang stylish dan fungsional, menjadikan produk ini nyaman dan praktis. Selain itu, lapisan khususnya dirancang untuk mencegah bahan menggumpal dan melar, menjaga kualitas dan penampilan pakaian tetap terjaga.`,
    },
    {
      id: "004",
      slug: "heattech-t-shirt-fleece-kerah-tinggi-lengan-panjang-women",
      name: "HEATTECH T-Shirt Fleece Kerah Tinggi Lengan Panjang",
      category: "Women's",
      price: 199_000,
      stock: 100,
      imageUrl: `https://image.uniqlo.com/UQ/ST3/id/imagesgoods/442063/item/idgoods_32_442063_3x4.jpg?width=369`,
      description: `The ‘HEATTECH’ fleece fabric provides the soft and comfortable feel of fleece, while the turtleneck design offers extra warmth, making it an ideal choice for cold weather.`,
    },
    {
      id: "005",
      slug: "jaket-parka-saku-proteksi-sinar-uv-women",
      name: "Jaket Parka Saku Proteksi Sinar UV (Water-Repellent)",
      category: "Women's",
      price: 499_000,
      stock: 3,
      imageUrl: `https://api.fastretailing.com/ugc/v1/uq/gl/OFFICIAL_IMAGES/240821063135_official_styling_120019476_c-480-640`,
      description: `Parka ringan dengan desain pocketable ini mampu melindungi dari hujan dan sinar matahari, dilengkapi teknologi perlindungan sinar UV dan lapisan water-repellent untuk melindungi dari hujan ringan. *Lapisan water-repellent ini tahan lebih lama namun tidak permanen. Dengan tingkat perlindungan UPF50+, parkanya cocok untuk olahraga maupun pakaian kasual sehari-hari.`,
    },
    {
      id: "006",
      slug: "kardigan-proteksi-sinar-uv-kerah-bulat-lengan-panjang-women",
      name: "Kardigan Proteksi Sinar UV Kerah Bulat Lengan Panjang",
      category: "Women's",
      price: 1_909_000,
      stock: 110,
      imageUrl: `https://image.uniqlo.com/UQ/ST3/id/imagesgoods/465484/item/idgoods_10_465484_3x4.jpg?width=369`,
      description: `Cardigan serbaguna ini terbuat dari bahan katun rayon yang lembut dan dilengkapi dengan teknologi UV Protection. Mudah dirawat karena dapat dicuci menggunakan mesin; pastikan menggunakan tas cucian tipe mesh dan memasukkan pakaian dalam keadaan terbalik. Setelah dicuci, bentangkan dalam bentuk aslinya untuk mengeringkan. Desainnya stylish dengan fit yang leluasa di bagian bodi dan lengan, serta dapat dipasang seluruh kancingnya untuk dikenakan sebagai pullover. Cocok dipakai di ruangan indoor yang dingin, kini hadir dengan ukuran lebih pendek, cocok dipadukan dengan berbagai bawahan. Pakaian serbaguna yang wajib dimiliki, dengan perlindungan UPF25.`,
    },
  ];
}
